const mongoose = require('mongoose');

const resumeSchema = new mongoose.Schema({
    username: { type: String, required: true },
    mobilenumber: { type: Number, required: true },
    email: { type: String, required: true },
    city: { type: String, required: true },
    state: { type: String, required: true },
    aboutme: { type: String, required: true },
    collegename: { type: String, required: true },
    colcity: { type: String, required: true },
    colstate: { type: String, required: true },
    colcgpa: { type: Number, required: true },
    colfield: { type: String, required: true },
    colfieldbranch: { type: String, required: true },
    colyear: { type: Number, required: true },
    schoolname12: { type: String, required: true },
    city12: { type: String, required: true },
    state12: { type: String, required: true },
    boardname12: { type: String, required: true },
    percentage12: { type: Number, required: true },
    schoolname10: { type: String, required: true },
    city10: { type: String, required: true },
    state10: { type: String, required: true },
    boardname10: { type: String, required: true },
    percentage10: { type: Number, required: true },
    projectname1: { type: String, required: true },
    p1gitlink: { type: String, required: true },
    p1skills: { type: [String], required: true },
    p1about: { type: String, required: true },
    projectname2: { type: String, required: true },
    p2gitlink: { type: String, required: true },
    p2skills: { type: [String], required: true },
    p2about: { type: String, required: true },
    frontend: { type: [String], required: true },
    backend: { type: [String], required: true },
    database: { type: [String], required: true },
    others: { type: [String], required: true },
    companynamecet: { type: [String], required: true },
    fieldcet: { type: [String], required: true },
    language: { type: [String], required: true },
    createdAt: { type: Date, default: Date.now }
})

module.exports = mongoose.model("resumedata", resumeSchema);